# Generated by Django 5.1.3 on 2025-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
