# Generated by Django 5.1.3 on 2025-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailconfirmation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
