# Generated by Django 5.1.3 on 2025-02-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_banner_img_alter_craftsmanship_img_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mission and History', max_length=200)),
                ('mission', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='author',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craftsmanship_list', to='products.category'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='craftsmanship/'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='mission_and_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aboutus'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='craft_items',
            field=models.ManyToManyField(blank=True, related_name='craftsmanship_lists', to='main.craftitem'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='craft_techniques',
            field=models.ManyToManyField(blank=True, related_name='craftsmanship_lists', to='main.crafttechnique'),
        ),
    ]
