# Generated by Django 5.1.3 on 2025-02-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutus_craftitem_crafttechnique_banner_author_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craft_items', to='products.category'),
        ),
        migrations.AddField(
            model_name='crafttechnique',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craft_techniques', to='products.category'),
        ),
    ]
