# Generated by Django 5.1.3 on 2025-02-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_craftitem_category_crafttechnique_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsmanshiplist',
            name='craft_items',
        ),
        migrations.RemoveField(
            model_name='crafttechnique',
            name='category',
        ),
        migrations.RemoveField(
            model_name='craftsmanshiplist',
            name='craft_techniques',
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='mission_and_history',
            new_name='about_us',
        ),
        migrations.DeleteModel(
            name='CraftItem',
        ),
        migrations.DeleteModel(
            name='CraftTechnique',
        ),
    ]
