# Generated by Django 5.1.3 on 2025-02-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_craftsmanshiplist_craft_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us', to='main.aboutus'),
        ),
        migrations.CreateModel(
            name='CraftsmanshipFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('craftsmanship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.craftsmanshiplist')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.craftsmanshipfeature')),
            ],
        ),
    ]
