# Generated by Django 5.1.3 on 2025-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ourteam_about_us_craftsmanshipfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='history_en',
            field=models.TextField(null=True, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='history_qq',
            field=models.TextField(null=True, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='history_ru',
            field=models.TextField(null=True, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='history_uz',
            field=models.TextField(null=True, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_qq',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_ru',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='mission_uz',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(default='Mission and History', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_qq',
            field=models.CharField(default='Mission and History', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(default='Mission and History', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(default='Mission and History', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='banner',
            name='author_en',
            field=models.CharField(default='Unknown', max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='banner',
            name='author_qq',
            field=models.CharField(default='Unknown', max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='banner',
            name='author_ru',
            field=models.CharField(default='Unknown', max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='banner',
            name='author_uz',
            field=models.CharField(default='Unknown', max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_en',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_qq',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_ru',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='name_uz',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_qq',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='text_qq',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='title_qq',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanshipfeature',
            name='key_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='craftsmanshipfeature',
            name='key_qq',
            field=models.CharField(max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='craftsmanshipfeature',
            name='key_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='craftsmanshipfeature',
            name='key_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='text_qq',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='title_qq',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='craftsmanshiplist',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='description_qq',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='name_qq',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_en',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_qq',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_ru',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_uz',
            field=models.CharField(max_length=450, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='profession_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='profession_qq',
            field=models.CharField(max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='profession_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='profession_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='text_qq',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='name_qq',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='history',
            field=models.TextField(verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='Mission and History', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='author',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=450, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='craftsmanship',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='craftsmanship',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='craftsmanshipfeature',
            name='key',
            field=models.CharField(max_length=255, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='craftsmanshiplist',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='craftsmanshiplist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name',
            field=models.CharField(max_length=450, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='profession',
            field=models.CharField(max_length=200, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
