# Generated by Django 5.1.3 on 2025-04-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutus_history_en_aboutus_history_qq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='history_qq',
            new_name='history_kaa',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='mission_qq',
            new_name='mission_kaa',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title_qq',
            new_name='title_kaa',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='author_qq',
            new_name='author_kaa',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='name_qq',
            new_name='name_kaa',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='text_qq',
            new_name='text_kaa',
        ),
        migrations.RenameField(
            model_name='craftsmanship',
            old_name='text_qq',
            new_name='text_kaa',
        ),
        migrations.RenameField(
            model_name='craftsmanship',
            old_name='title_qq',
            new_name='title_kaa',
        ),
        migrations.RenameField(
            model_name='craftsmanshipfeature',
            old_name='key_qq',
            new_name='key_kaa',
        ),
        migrations.RenameField(
            model_name='craftsmanshiplist',
            old_name='text_qq',
            new_name='text_kaa',
        ),
        migrations.RenameField(
            model_name='craftsmanshiplist',
            old_name='title_qq',
            new_name='title_kaa',
        ),
        migrations.RenameField(
            model_name='featureitem',
            old_name='description_qq',
            new_name='description_kaa',
        ),
        migrations.RenameField(
            model_name='featureitem',
            old_name='name_qq',
            new_name='name_kaa',
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='name_qq',
            new_name='name_kaa',
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='profession_qq',
            new_name='profession_kaa',
        ),
        migrations.RenameField(
            model_name='ourteam',
            old_name='text_qq',
            new_name='text_kaa',
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='name_qq',
            new_name='name_kaa',
        ),
    ]
