# Generated by Django 5.1.3 on 2025-03-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='image',
        ),
    ]
