# Generated by Django 5.1.3 on 2025-04-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_workshop_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='image_360',
        ),
        migrations.AddField(
            model_name='workshop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkshopImage360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_360', models.ImageField(upload_to='360_images/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workshop.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'user')},
            },
        ),
    ]
